# Build - first phase
FROM golang:1.18-alpine as builder
RUN mkdir /build
WORKDIR /build
RUN apk update && apk add --no-cache build-base linux-headers git bash ca-certificates libstdc++
COPY . .
RUN make evm-dbg

# Runtime -  second phase.
FROM alpine:3.15.7
RUN mkdir /app
WORKDIR /app
RUN apk update && apk add --no-cache bash=5.1.16-r0 libstdc++
COPY --from=builder /build/build/bin/ /app
SHELL ["/bin/bash", "-c"]
RUN chmod +x ./evm
ENTRYPOINT [ "/bin/bash", "-l", "-c" ]
CMD [ "./evm t8n --server.mode --server.port 3002" ]


# default
EXPOSE 3002